""" 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t
"""

def difference_in_strings(s: str,t: str) -> str:
    if s == '':
        return t
    s = sorted(s)
    t = sorted(t)
    for i,char in enumerate(s):
        if char != t[i]:
            return t[i]
    return t.pop()


    
def main():
    test_cases = [
        {"input1":"abcd","input2":"abcde","expected":"e"},
        {"input1":"","input2":"y","expected":"y"},
        {"input1":"a","input2":"aa","expected":"a"}
    ]
    
    for test_case in test_cases:
        result = difference_in_strings(test_case['input1'], test_case['input2'])
        status = result == test_case['expected']
        print(f"{test_case['input1']} {test_case['input2']} {result} {status}")
        
if __name__ == '__main__':
    main()